name: Update arxiv papers
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Run pipeline
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ vars.BASE_URL }}
          MODEL: ${{ vars.MODEL }}
          TOP_N: ${{ vars.TOP_N }}
          KEYWORDS: ${{ vars.KEYWORDS }}
        run: |
          mkdir data
          python run.py run_pipeline

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: "push all update"
          files: "./*"
          rebase: 'true'
          name: 'zhangtaochn'
          email: 'zhangtao-1994@qq.com'
