name: Update arxiv papers
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Run pipeline
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ vars.BASE_URL }}
          MODEL: ${{ vars.MODEL }}
          TOP_N: ${{ vars.TOP_N }}
          KEYWORDS: ${{ vars.KEYWORDS }}
        run: |
          mkdir data
          python run.py run_pipeline

      - name: Commit changes
        run: |
          git config user.name "zhangtaochn"
          git config user.email "zhangtao-1994@qq.com"
          git add web/all_papers.json data/*
          git commit -m "Arxiv Papers Update" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push https://zhangtaochn:${{ secrets.ACCESS_TOKEN }}@github.com/zhangtaochn/daily-arxiv.git HEAD:main
